name: React CD Pipeline

on: 
  workflow_run:
    workflows: ["React CI Pipeline"]  # Trigger after CI pipeline completes successfully
    types:
      - completed

jobs:
  build-and-deploy:
    runs-on: [self-hosted, linux]  # Self-hosted runner

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Build the application
      - name: Build Application
        run: npm run build

      # Step 5: Download Artifact from the CI pipeline
      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: build  # Artifact name from CI pipeline

      # Step 6: Deploy the application to AWS EC2
      - name: Deploy Application to AWS EC2
        run: |
          echo "Deploying to AWS EC2..."
          
          # Install AWS CLI (if not installed already)
          sudo apt-get install awscli -y
          
          # Configure AWS CLI with IAM User Access Key and Secret Key (or use AWS IAM Role)
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1  # Set your region

          # Copy build folder to EC2 instance using SCP (Secure Copy Protocol)
          scp -i /path/to/your/private-key.pem -r ./dist ec2-user@your-ec2-ip:/var/www/html/my-app

          # SSH into EC2 and restart the server (optional, depending on server setup)
          ssh -i /path/to/your/private-key.pem ec2-user@your-ec2-ip << EOF
            cd /var/www/html/my-app
            npm install --production
            pm2 restart my-app  # Assuming you use PM2 for process management
          EOF
